- name: "Install necessary packages for Docker for Debian"
  ansible.builtin.apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    update_cache: yes
    state: latest

- name: "Add Docker repo key for Debian"
  ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: "Add Docker repo for Debian"
  ansible.builtin.shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: "Install Docker for Debian"
  ansible.builtin.apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    update_cache: yes
    state: latest