- name: set hostname
  ansible.builtin.shell: "hostnamectl set-hostname {{inventory_hostname}}"

- name: change /etc/hosts
  ansible.builtin.template:
    src: ./templates/etc-host.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"

- name: update & upgrade
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
    state: latest

- name: install necessary packages
  ansible.builtin.apt:
    pkg:
    - curl
    - apt-transport-https
    - git
    - iptables-persistent
    update_cache: yes
    state: latest

- name: disable SWAP (1/2)
  ansible.builtin.shell: swapoff -a

- name: disable SWAP (2/2)
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: adding modules (1/2)
  ansible.builtin.template:
    src: ./templates/modules-k8s-conf.j2
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: "0644"

- name: adding modules (2/2)
  ansible.builtin.shell: |
    modprobe br_netfilter
    modprobe overlay

- name: changes linux core params (1/2)
  ansible.builtin.template:
    src: ./templates/sysctld-k8s-conf.j2
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: "0644"

- name: changes linux core params (2/2)
  ansible.builtin.shell: |
    sysctl --system

- name: install Docker (1/6)
  ansible.builtin.apt:
    pkg:
    - ca-certificates
    - gnupg
    - lsb-release
    update_cache: yes
    state: latest

- name: install Docker (2/6)
  ansible.builtin.shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

- name: install Docker (3/6)
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: install Docker (4/6)
  ansible.builtin.apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    update_cache: yes
    state: latest

- name: install Docker (5/6)
  ansible.builtin.template:
    src: ./templates/docker-daemon-json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"

- name: install Docker (6/6)
  ansible.builtin.systemd:
    state: restarted
    name: docker

- name: adding Google cloud repo
  ansible.builtin.shell: |
    sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: install kubectl
  ansible.builtin.apt:
    pkg:
    - kubectl
    update_cache: yes
    state: latest