---
- name: AWS self-managed k8s cluster configuration
  hosts: all
  become: true
  roles:
    - role: node-prepare
      tags:
        - node-prepare
        - cluster-setup
    - role: cluster-setup
      tags:
        - cluster-setup
    - role: node-add
      tags:
        - node-add