- name: install kube packages on master
  ansible.builtin.apt:
    pkg:
    - kubelet={{cluster_version}}
    - kubeadm={{cluster_version}}
    - kubectl={{cluster_version}}
    update_cache: yes

- name: permit kube in iptables on master (1/2)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "6443"
      - "2379:2380"
      - "10250:10252"
    jump: ACCEPT
    comment: "K8s master node rules"

- name: permit kube in iptables on master (2/2)
  ansible.builtin.shell: |
    iptables-save > /etc/iptables/rules.v4

- name: init kubernetes cluster on master (1/2)
  ansible.builtin.shell: |
    kubeadm init --pod-network-cidr={{pod_net}} --service-cidr={{svc_net}} --ignore-preflight-errors="NumCPU"

- name: init kubernetes cluster on master (2/2)
  ansible.builtin.shell: |
    echo "export KUBECONFIG=/etc/kubernetes/admin.conf" >> /etc/environment

- name: install CNI (1/2)
  ansible.builtin.template:
    src: ./templates/cni-flannel.j2
    dest: /tmp/cni-flannel.yml
    owner: root
    group: root
    mode: "0644"

- name: install CNI (2/2)
  ansible.builtin.shell: |
    kubectl apply -f /tmp/cni-flannel.yml

- name: generate join token
  ansible.builtin.shell: |
    kubeadm token create --print-join-command
  register: kubeadm_join_out

- name: set kubeadm_join var
  ansible.builtin.set_fact:
    kubeadm_join: "{{kubeadm_join_out.stdout}}"