- name: install kube packages on worker
  ansible.builtin.apt:
    pkg:
    - kubelet={{cluster_version}}
    - kubeadm={{cluster_version}}
    update_cache: yes

- name: permit kube in iptables on worker (1/1)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "10250"
      - "30000:32767"
    jump: ACCEPT
    comment: "K8s worker node rules"

- name: permit kube in iptables on worker (2/2)
  ansible.builtin.shell: |
    iptables-save > /etc/iptables/rules.v4

- name: join worker to cluster
  ansible.builtin.shell: |
    {{hostvars['k8s-aws-master0']['kubeadm_join']}}